# Generated by Django 5.1.2 on 2024-10-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='district_name',
            field=models.CharField(blank=True, default='undefined', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, default='undefined', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='group_village_head_name',
            field=models.CharField(blank=True, default='undefined', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='household_id',
            field=models.CharField(blank=True, default='undefined', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='national_id',
            field=models.CharField(blank=True, default='undefined', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='phoneNumber',
            field=models.CharField(blank=True, default='undefined', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='traditional_authority_name',
            field=models.CharField(blank=True, default='undefined', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='village_name',
            field=models.CharField(blank=True, default='undefined', max_length=30, null=True),
        ),
    ]
