# Generated by Django 5.1.2 on 2024-10-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_person_district_name_alter_person_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Phase_Name',
            field=models.CharField(blank=True, default='undefined', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='enrolled_HHs',
            field=models.CharField(blank=True, default='undefined', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, default='undefined', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_HHs',
            field=models.CharField(blank=True, default='undefined', max_length=30, null=True),
        ),
    ]
